<?
  include(locate_template('factories/blockquote.php'));
  include(locate_template('factories/cta-block.php'));
  include(locate_template('factories/image-block.php'));
  include(locate_template('factories/display-card.php'));
  include(locate_template('factories/header-image.php'));
  include(locate_template('factories/image.php'));
  include(locate_template('factories/tooltip.php'));
  include(locate_template('factories/text-columns.php'));
?>
