<?
  include(locate_template('factories/factory-blockquote.php'));
  include(locate_template('factories/factory-cta-block.php'));
  include(locate_template('factories/factory-image-block.php'));
  include(locate_template('factories/factory-header-image.php'));
  include(locate_template('factories/factory-image.php'));
  include(locate_template('factories/factory-tooltip.php'));
  include(locate_template('factories/factory-text-columns.php'));
?>
